// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EquipmentManager.Models
{
    public partial class AssignmentsDetail
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public string ColleagueId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RequestingDepartment { get; set; }
        public string RequestedBy { get; set; }
        public string AssignedBy { get; set; }
        public DateTime AssignedDate { get; set; }
        public string EquipType { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string SerialNum { get; set; }
        public string ServiceTag { get; set; }
        public int UnassignedBy { get; set; }
        public DateTime UnassignedDate { get; set; }
    }
}