// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EquipmentManager.Models
{
    public partial class Department
    {
        Department()
        {
            Assignments = new HashSet<Assignment>();
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Assignment> Assignments { get; set; }
    }
}