// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EquipmentManager.Models
{
    public partial class Equipment
    {
        public int Id { get; set; }
        public string EquipType { get; set; }
        public string Vendor { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string SubModel { get; set; }
        public string SerialNum { get; set; }
        public string ServiceTag { get; set; }
        public string InvoiceNum { get; set; }
        public DateTime DateReceived { get; set; }
        public string RequestingDept { get; set; }
        public string RequestedBy { get; set; }
        public bool? Warranty { get; set; }
        public DateTime? DecommissionDate { get; set; }
        public bool? DecommissionStatus { get; set; }
        public DateTime? DestroyDate { get; set; }
        public bool? DestroyStatus { get; set; }
    }
}