// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using EquipmentManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EquipmentManager
{
    public partial class UcInventoryContext : DbContext
    {
        public UcInventoryContext()
        {
        }

        public UcInventoryContext(DbContextOptions<UcInventoryContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Assignment> Assignment { get; set; }
        public virtual DbSet<AssignmentsDetail> AssignmentsDetail { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentType> EquipmentType { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Assignment>(entity =>
            {
                entity.Property(e => e.AssignedDate).HasColumnType("datetime");

                entity.Property(e => e.RequestingDepartment)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.UnassignedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<AssignmentsDetail>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("AssignmentsDetail");

                entity.Property(e => e.AssignedBy).IsRequired();

                entity.Property(e => e.AssignedDate).HasColumnType("date");

                entity.Property(e => e.ColleagueId).IsRequired();

                entity.Property(e => e.EquipType).HasMaxLength(200);

                entity.Property(e => e.FirstName)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.LastName)
                    .HasMaxLength(80)
                    .IsUnicode(false);

                entity.Property(e => e.Manufacturer).HasMaxLength(250);

                entity.Property(e => e.Model)
                    .IsRequired()
                    .HasMaxLength(150);

                entity.Property(e => e.RequestedBy)
                    .IsRequired()
                    .HasMaxLength(250);

                entity.Property(e => e.RequestingDepartment).IsRequired();

                entity.Property(e => e.SerialNum)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.ServiceTag).HasMaxLength(50);

                entity.Property(e => e.UnassignedDate).HasColumnType("date");
            });

            modelBuilder.Entity<Department>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Employee>(entity =>
            {
                entity.Property(e => e.ColleaugeId)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(49)
                    .IsUnicode(false)
                    .HasComputedColumnSql("(concat([FirstName],[LastName]+'@ucwv.edu'))");

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(41)
                    .IsUnicode(false)
                    .HasComputedColumnSql("(concat([FirstName],' ',[LastName]))");
            });

            modelBuilder.Entity<Equipment>(entity =>
            {
                entity.Property(e => e.DateReceived).HasColumnType("datetime");

                entity.Property(e => e.DecommissionDate).HasColumnType("datetime");

                entity.Property(e => e.DestroyDate).HasColumnType("datetime");

                entity.Property(e => e.EquipType).HasMaxLength(200);

                entity.Property(e => e.InvoiceNum)
                    .IsRequired()
                    .HasMaxLength(25);

                entity.Property(e => e.Manufacturer).HasMaxLength(250);

                entity.Property(e => e.Model)
                    .IsRequired()
                    .HasMaxLength(150);

                entity.Property(e => e.RequestedBy)
                    .IsRequired()
                    .HasMaxLength(250);

                entity.Property(e => e.RequestingDept)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.SerialNum)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.ServiceTag).HasMaxLength(50);

                entity.Property(e => e.SubModel).HasMaxLength(50);

                entity.Property(e => e.Vendor).HasMaxLength(200);
            });

            modelBuilder.Entity<EquipmentType>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100);
            });

            modelBuilder.Entity<Manufacturer>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(250);
            });

            modelBuilder.Entity<Repair>(entity =>
            {
                entity.Property(e => e.City)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.ContactEmail).HasMaxLength(100);

                entity.Property(e => e.ContactPhone).HasMaxLength(100);

                entity.Property(e => e.Country).HasMaxLength(100);

                entity.Property(e => e.DateReturned).HasColumnType("date");

                entity.Property(e => e.DateShipped).HasColumnType("date");

                entity.Property(e => e.Recipient)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.ReplacementSerialNumber).HasMaxLength(100);

                entity.Property(e => e.RequestedBy)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.RmaNum)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.StreetAddress1)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.StreetAddress2).HasMaxLength(100);

                entity.Property(e => e.StreetAddress3).HasMaxLength(100);

                entity.Property(e => e.TrackingNum)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Zip)
                    .IsRequired()
                    .HasMaxLength(10);
            });

            modelBuilder.Entity<State>(entity =>
            {
                entity.Property(e => e.Abbreviation)
                    .IsRequired()
                    .HasMaxLength(4);

                entity.Property(e => e.Name).IsRequired();
            });

            modelBuilder.Entity<Vendor>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(200);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}